Update changelog for Fields page performance
apollographql/apollo-studio-community pull request #211
Opened 2022-11-17 18:16 UTC by bpuckhaber

2022-11-17 18:16 UTC, apollo-cla commented
@bpuckhaber: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2022-11-18 02:37 UTC, timbotnik commented on CHANGELOG.md
> +| We have improved the performance of the Fields page to better support graphs with a large number of fields (> 1000).
I'd say if we include this change that we should be super explicit about fixing _part_ of the problem but not all of the problem, and that we're working on solutions to better handle the other issues.  Alternatively, wait until we've finished the improvements to handling the stats loading / errors UX and announce them together.

2022-12-06 16:16 UTC, nkhi requested changes
I think it should be

"We have improved the scrolling performance of the Fields page for graphs with over one thousand fields. Additionally, timeout requests on the field page for graphs with over five thousand fields omit operation usage and field execution metrics from the page."

My two cents

2022-12-09 03:38 UTC, timbotnik approved these changes
Updated with some changes!

2022-12-09 03:38 UTC, timbotnik commented on CHANGELOG.md
> +| We have improved the performance of the Fields page to better support graphs with a large number of fields (> 1000). Also, Fields page request timeouts experienced by large graphs (> 5000 fields) a
```suggestion
| We have improved the performance of the Fields page to better support graphs with a large number of fields. 
 For the largest of graphs (> 5000 fields) we now omit usage metrics and encourage you to navigate to [individual field pages](https://www.apollographql.com/blog/backend/performance/field-level-insights-in-studio/) for field-level insights.
```

2022-12-09 18:16 UTC, nkhi commented
I think omitting the word `scrolling` from `performance` in the first sentence makes it unclear to me. Everything else LGTM. Your call!

2022-12-09 18:17 UTC, nkhi approved these changes

2022-12-09 18:17 UTC, nkhi commented
I wonder if we could use Astros pagination to bring back in-list-metrics for >5000 field schemas?

2022-12-09 18:38 UTC, merged